### ISSUE TITLE
Unable To Mount iso,image file on Android?

### ISSUE THREAD

**Issue by Winchester95** [schellingb/dosbox-pure#284]
it is working fine on windows 10 but on android when i try to load windows 98 or any other iso,img file it says unable to open image file

**Comment by michaeljsiena** [comment]
I have the same issue.

**Comment by Winchester95** [comment]
> I have the same issue.

If you find a solution plz let me know

**Comment by schellingb** [comment]
Hey there, thanks for reporting. I fixed some Android related bugs in the new 0.9.6 hotfix release, can you try it out? Either download it from [the release page here](../releases/tag/0.9.6) (only ARM64 build available) or from the RetroArch Online Core Updater once it arrives there in a few hours.

**Comment by michaeljsiena** [comment]
Thank you - this is a really cool project so I appreciate your work!

I was able to install Windows 98 (with an error at the very end) on Android using the latest nightly build of Retroarch. I can boot into Windows after installation but get an error when using the file explorer. I have attached screenshots of both errors. Hopefully this helps!

![Screenshot_2022-06-26-10-41-36-99_a845f06d2c9842610668be6995f9e34f.jpg](https://user-images.githubusercontent.com/72791922/175811186-f18f991e-cfd6-49ce-aa5d-5273cef06d77.jpg)

![Screenshot_2022-06-26-10-04-36-75_a845f06d2c9842610668be6995f9e34f.jpg](https://user-images.githubusercontent.com/72791922/175811191-ef1a0195-13c4-4d8b-ae40-7221178e43af.jpg)

**Comment by Winchester95** [comment]
> > Hey there, thanks for reporting. I fixed some Android related bugs in the new 0.9.6 hotfix release, can you try it out? Either download it from [the release page here](../releases/tag/0.9.6) (only ARM64 build available) or from the RetroArch Online Core Updater once it arrives there in a few hours.
> 
> Thank you - this is a really cool project so I appreciate your work!
> 
> I was able to install Windows 98 on Android using the latest nightly build of RetroArch (with an error at the very end of the installation process, however). I am still able to boot into Windows after, but I get an error when attempting to use the file explorer. I have attached screenshots of both errors. Hopefully this helps!
> 
> ![Screenshot_2022-06-26-10-41-36-99_a845f06d2c9842610668be6995f9e34f.jpg](https://user-images.githubusercontent.com/72791922/175811186-f18f991e-cfd6-49ce-aa5d-5273cef06d77.jpg)
> 
> ![Screenshot_2022-06-26-10-04-36-75_a845f06d2c9842610668be6995f9e34f.jpg](https://user-images.githubusercontent.com/72791922/175811191-ef1a0195-13c4-4d8b-ae40-7221178e43af.jpg)

i tried windows 95 also but same error

**Comment by michaeljsiena** [comment]
> > > Hey there, thanks for reporting. I fixed some Android related bugs in the new 0.9.6 hotfix release, can you try it out? Either download it from [the release page here](../releases/tag/0.9.6) (only ARM64 build available) or from the RetroArch Online Core Updater once it arrives there in a few hours.
> > 
> > 
> > Thank you - this is a really cool project so I appreciate your work!
> > I was able to install Windows 98 on Android using the latest nightly build of RetroArch (with an error at the very end of the installation process, however). I am still able to boot into Windows after, but I get an error when attempting to use the file explorer. I have attached screenshots of both errors. Hopefully this helps!
> > ![Screenshot_2022-06-26-10-41-36-99_a845f06d2c9842610668be6995f9e34f.jpg](https://user-images.githubusercontent.com/72791922/175811186-f18f991e-cfd6-49ce-aa5d-5273cef06d77.jpg)
> > ![Screenshot_2022-06-26-10-04-36-75_a845f06d2c9842610668be6995f9e34f.jpg](https://user-images.githubusercontent.com/72791922/175811191-ef1a0195-13c4-4d8b-ae40-7221178e43af.jpg)
> 
> i tried windows 95 also but same error

I got it working. I simply set up my copy Windows 98 on my PC, then transferred the image to my phone. Everything seems to be working now. Just tried the demo for Blood II: The Chosen and it works!

**Comment by wn2000** [comment]
> I got it working. I simply set up my copy Windows 98 on my PC, then transferred the image to my phone. Everything seems to be working now. Just tried the demo for Blood II: The Chosen and it works!

Unfortunately this method did not work for me on arm Linux. I installed Windows 98SE inside RetroArch on my Windows 10 PC, then transferred the generated `.img` file to arm Linux (RK3328). But I'm still getting "page fault" errors after booting into Windows 98.

**Comment by Winchester95** [comment]
> > > > Hey there, thanks for reporting. I fixed some Android related bugs in the new 0.9.6 hotfix release, can you try it out? Either download it from [the release page here](../releases/tag/0.9.6) (only ARM64 build available) or from the RetroArch Online Core Updater once it arrives there in a few hours.
> > > 
> > > 
> > > Thank you - this is a really cool project so I appreciate your work!
> > > I was able to install Windows 98 on Android using the latest nightly build of RetroArch (with an error at the very end of the installation process, however). I am still able to boot into Windows after, but I get an error when attempting to use the file explorer. I have attached screenshots of both errors. Hopefully this helps!
> > > ![Screenshot_2022-06-26-10-41-36-99_a845f06d2c9842610668be6995f9e34f.jpg](https://user-images.githubusercontent.com/72791922/175811186-f18f991e-cfd6-49ce-aa5d-5273cef06d77.jpg)
> > > ![Screenshot_2022-06-26-10-04-36-75_a845f06d2c9842610668be6995f9e34f.jpg](https://user-images.githubusercontent.com/72791922/175811191-ef1a0195-13c4-4d8b-ae40-7221178e43af.jpg)
> > 
> > 
> > i tried windows 95 also but same error
> 
> I got it working. I simply set up my copy Windows 98 on my PC, then transferred the image to my phone. Everything seems to be working now. Just tried the demo for Blood II: The Chosen and it w

**Comment by Winchester95** [comment]
> > > > Hey there, thanks for reporting. I fixed some Android related bugs in the new 0.9.6 hotfix release, can you try it out? Either download it from [the release page here](../releases/tag/0.9.6) (only ARM64 build available) or from the RetroArch Online Core Updater once it arrives there in a few hours.
> > > 
> > > 
> > > Thank you - this is a really cool project so I appreciate your work!
> > > I was able to install Windows 98 on Android using the latest nightly build of RetroArch (with an error at the very end of the installation process, however). I am still able to boot into Windows after, but I get an error when attempting to use the file explorer. I have attached screenshots of both errors. Hopefully this helps!
> > > ![Screenshot_2022-06-26-10-41-36-99_a845f06d2c9842610668be6995f9e34f.jpg](https://user-images.githubusercontent.com/72791922/175811186-f18f991e-cfd6-49ce-aa5d-5273cef06d77.jpg)
> > > ![Screenshot_2022-06-26-10-04-36-75_a845f06d2c9842610668be6995f9e34f.jpg](https://user-images.githubusercontent.com/72791922/175811191-ef1a0195-13c4-4d8b-ae40-7221178e43af.jpg)
> > 
> > 
> > i tried windows 95 also but same error
> 
> I got it working. I simply set up my copy Windows 98 on my PC, then transferred the image to my phone. Everything seems to be working now. Just tried the demo for Blood II: The Chosen and it works!

its working now thanx!

**Comment by schellingb** [comment]
I'm closing this issue now. Problems regarding "page faults" and other issues with the CPU emulation on ARM devices should be posted in #288. Thanks!
